// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://albhpkdjpygzdhkeggmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsYmhwa2RqcHlnemRoa2VnZ21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjE2NjksImV4cCI6MjA3MDY5NzY2OX0.pLtsDQ1RsuiUZOhcL2vU4ynvgfoL8b24m1MUAd10zrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});